name: 'Policy Check: EMR Release Label'

on: [pull_request]

defaults:
  run:
    shell: bash
    
env:
  TARGET_RELEASE_LABEL: 6.13.0

permissions:
  id-token: write
  contents: read 
  pull-requests: write

jobs:
  pr_checks:
    name: 'PR Checks'
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/composite/tpl
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: policy-check-release-label.sh
