name: "Policy Check: TPL files"
description: "Runs policy checks on tpl files"

inputs:
  github-token:
    description: "Github Token"
    required: true
  script:
    description: "Policy script to execute"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v29.0.7-uhg
      with:
        files: '**/*.tpl'
        
    - name: Validate Policy
      id: validate-policy 
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: bash ./.github/scripts/${{inputs.script}} 
      
    - name: Update Pull Request
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.summary
          })
      
    - name: Result
      if: steps.changed-files.outputs.any_changed == 'true' && steps.validate-policy.outputs.result != 'pass'
      shell: bash
      run: exit 1
